---
name: Run website-stalker

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 22 * * *'

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      WEBSITE_STALKER_FROM: ${{ secrets.WEBSITE_STALKER_FROM }}
    steps:
      - uses: EdJoPaTo/website-stalker-github-action@v1

      - uses: actions/checkout@v3

      - name: Check website-stalker config
        run: website-stalker check

      - name: Run website-stalker
        run: website-stalker run --all --commit

      - if: always()
        run: git push
